apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: parentpal-backend
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/backend
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
